review
created-by-pavel/ToDoList pull request #1
Opened 2022-01-03 16:20 UTC by created-by-pavel

2022-01-03 17:14 UTC, FrediKats requested changes

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +namespace ToDoList.Client
Отступ лучше добавить после юзинга.

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +            _drawing = new Drawing();
Такие штуки можно прокидывать аргументами, чтобы была возможность конфигурить и заменить реализацию. Иначе нет смысла в DIP

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +        private void ReadCommands()
Это не только Read, но и Execute)

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +                    _service.AddTask(args);
На уровне сервисов я бы ожидал, чтобы работа была уже с осознанными аргументами, а не просто пихался лист.

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +                    _service.AddTask(args);
Ну и проверка кол-ва аргументов.

2022-01-03 17:14 UTC, FrediKats commented on Client/ConsoleCommands.cs
> +                    _service.AddDeadLine(deadlineArgs[0], DateTime.Parse(deadLineTime));
TryParse + бросание ошибки понятной.

2022-01-03 17:14 UTC, FrediKats commented on Models/SubTask.cs
> +            Id = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
А почему просто не сделать ToString?)

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +        public void Save()
Ещё бы возможность конфигурить куда сохраняется)

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +                }
Выглядит как что-то, что можно инкапсулировать внутри таски.

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +            foreach (var task in _tasks)
Можно сделать Find и уменьшить сложенность.

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +            if (group.Tasks.Contains(task)) group.Tasks.Remove(task);
Лучше переносить тело if'а на новую строку, а то сложно читать, не понятно что там ещё продолжение есть.

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +            if (task == null) throw new ToDoListException("cant find");
Назвал бы тогда GetTask.

2022-01-03 17:14 UTC, FrediKats commented on Services/ToDoListService.cs
> +            List<Task> tasks = new ();
.SelectMany?

2022-01-05 06:26 UTC, created-by-pavel commented on Models/SubTask.cs
> +            Id = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
я хотел короткий id, но все еще guid и подсмотрел у умельцев с cyberforum'а )

2022-01-06 07:38 UTC, FrediKats approved these changes

2022-01-06 09:12 UTC, merged